name: Testes Unitarios

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  testes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Rodar testes unitarios
        run: node src/App.test.node.js
